### ISSUE TITLE
Issue with the models

### ISSUE THREAD

**Issue by fengv1976** [EllairaT/DRA#7]
In the Api branch, I create the file at ./pages/api/job.js and current having an issue reading the model as the API can run normally for errors but when using the model it comes up with "TypeError: Schema is not a constructor".

**Comment by EllairaT** [comment]
issue was that there were invalid types within the job and assessment models. 

![image](https://user-images.githubusercontent.com/62170666/129284512-9f19b552-f09a-47ec-9626-9c68baf7328b.png)
![image](https://user-images.githubusercontent.com/62170666/129284533-0fd434ff-e2ad-4791-81f5-efc080b05805.png)

We will look into nested schemas, but for now assume that the array of assessments is an array of strings (assessment id's)
